---
  # MD013/line-length - Line length
  MD013:
    length: 150
    tables: false
    code_blocks: false
  # MD024/no-duplicate-heading - Multiple headings with the same content
  MD024:
    siblings_only: true
  # MD033/no-inline-html - Inline HTML
  MD033:
    allowed_elements:
      - "a"
      - "br"
      - "pre"